name: Heroku
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - name: Development Code
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Packages
        run: npm install
        working-directory: ./client

      - name: Install Web3
        run: npm install web3
        working-directory: ./client

      - name: Build page
        run: npm run build
        working-directory: ./client

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          args: deploy --dir=build --prod
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: 'ticketplaces'
          heroku_email: 'spirit_holder@hotmail.com'
          publish_dir: ./client/build